//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratcolInterface.StratcolAhv {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
        "wsdl", ConfigurationName="StratcolAhv.outputAhvTransPortType")]
    public interface outputAhvTransPortType {
        
        // CODEGEN: Generating message contract since the operation outputAhvTrans is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="outputAhvTrans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratcolInterface.StratcolAhv.outputAhvTransResponse outputAhvTrans(StratcolInterface.StratcolAhv.outputAhvTransRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
        "wsdl")]
    public partial class authenticateClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
        "wsdl")]
    public partial class ahvTranDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string user_idField;
        
        private string tran_statusField;
        
        private string acb_statusField;
        
        private string id_no_matchField;
        
        private string acc_no_matchField;
        
        private string acc_openField;
        
        private string allow_debitField;
        
        private string allow_creditField;
        
        private string open3_monthsField;
        
        private string surname_matchField;
        
        private string initials_matchField;
        
        private string otidField;
        
        private string batch_refField;
        
        private string surnameField;
        
        private string initialsField;
        
        private string id_noField;
        
        private string branch_codeField;
        
        private string account_noField;
        
        private string status_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tran_status {
            get {
                return this.tran_statusField;
            }
            set {
                this.tran_statusField = value;
                this.RaisePropertyChanged("tran_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string acb_status {
            get {
                return this.acb_statusField;
            }
            set {
                this.acb_statusField = value;
                this.RaisePropertyChanged("acb_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string id_no_match {
            get {
                return this.id_no_matchField;
            }
            set {
                this.id_no_matchField = value;
                this.RaisePropertyChanged("id_no_match");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string acc_no_match {
            get {
                return this.acc_no_matchField;
            }
            set {
                this.acc_no_matchField = value;
                this.RaisePropertyChanged("acc_no_match");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string acc_open {
            get {
                return this.acc_openField;
            }
            set {
                this.acc_openField = value;
                this.RaisePropertyChanged("acc_open");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string allow_debit {
            get {
                return this.allow_debitField;
            }
            set {
                this.allow_debitField = value;
                this.RaisePropertyChanged("allow_debit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string allow_credit {
            get {
                return this.allow_creditField;
            }
            set {
                this.allow_creditField = value;
                this.RaisePropertyChanged("allow_credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string open3_months {
            get {
                return this.open3_monthsField;
            }
            set {
                this.open3_monthsField = value;
                this.RaisePropertyChanged("open3_months");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string surname_match {
            get {
                return this.surname_matchField;
            }
            set {
                this.surname_matchField = value;
                this.RaisePropertyChanged("surname_match");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string initials_match {
            get {
                return this.initials_matchField;
            }
            set {
                this.initials_matchField = value;
                this.RaisePropertyChanged("initials_match");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string otid {
            get {
                return this.otidField;
            }
            set {
                this.otidField = value;
                this.RaisePropertyChanged("otid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string batch_ref {
            get {
                return this.batch_refField;
            }
            set {
                this.batch_refField = value;
                this.RaisePropertyChanged("batch_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string surname {
            get {
                return this.surnameField;
            }
            set {
                this.surnameField = value;
                this.RaisePropertyChanged("surname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string initials {
            get {
                return this.initialsField;
            }
            set {
                this.initialsField = value;
                this.RaisePropertyChanged("initials");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string id_no {
            get {
                return this.id_noField;
            }
            set {
                this.id_noField = value;
                this.RaisePropertyChanged("id_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string branch_code {
            get {
                return this.branch_codeField;
            }
            set {
                this.branch_codeField = value;
                this.RaisePropertyChanged("branch_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string account_no {
            get {
                return this.account_noField;
            }
            set {
                this.account_noField = value;
                this.RaisePropertyChanged("account_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string status_date {
            get {
                return this.status_dateField;
            }
            set {
                this.status_dateField = value;
                this.RaisePropertyChanged("status_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
        "wsdl")]
    public partial class ahvTransRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string file_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string file_code {
            get {
                return this.file_codeField;
            }
            set {
                this.file_codeField = value;
                this.RaisePropertyChanged("file_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputAhvTransRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
            "wsdl")]
        public StratcolInterface.StratcolAhv.authenticateClient authenticateClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
            "wsdl", Order=0)]
        public StratcolInterface.StratcolAhv.ahvTransRequest ahvTransRequest;
        
        public outputAhvTransRequest() {
        }
        
        public outputAhvTransRequest(StratcolInterface.StratcolAhv.authenticateClient authenticateClient, StratcolInterface.StratcolAhv.ahvTransRequest ahvTransRequest) {
            this.authenticateClient = authenticateClient;
            this.ahvTransRequest = ahvTransRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class outputAhvTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAhv." +
            "wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trans", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratcolInterface.StratcolAhv.ahvTranDetails[] arrayOfTrans;
        
        public outputAhvTransResponse() {
        }
        
        public outputAhvTransResponse(StratcolInterface.StratcolAhv.ahvTranDetails[] arrayOfTrans) {
            this.arrayOfTrans = arrayOfTrans;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface outputAhvTransPortTypeChannel : StratcolInterface.StratcolAhv.outputAhvTransPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class outputAhvTransPortTypeClient : System.ServiceModel.ClientBase<StratcolInterface.StratcolAhv.outputAhvTransPortType>, StratcolInterface.StratcolAhv.outputAhvTransPortType {
        
        public outputAhvTransPortTypeClient() {
        }
        
        public outputAhvTransPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public outputAhvTransPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public outputAhvTransPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public outputAhvTransPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratcolInterface.StratcolAhv.outputAhvTransResponse StratcolInterface.StratcolAhv.outputAhvTransPortType.outputAhvTrans(StratcolInterface.StratcolAhv.outputAhvTransRequest request) {
            return base.Channel.outputAhvTrans(request);
        }
        
        public StratcolInterface.StratcolAhv.ahvTranDetails[] outputAhvTrans(StratcolInterface.StratcolAhv.authenticateClient authenticateClient, StratcolInterface.StratcolAhv.ahvTransRequest ahvTransRequest) {
            StratcolInterface.StratcolAhv.outputAhvTransRequest inValue = new StratcolInterface.StratcolAhv.outputAhvTransRequest();
            inValue.authenticateClient = authenticateClient;
            inValue.ahvTransRequest = ahvTransRequest;
            StratcolInterface.StratcolAhv.outputAhvTransResponse retVal = ((StratcolInterface.StratcolAhv.outputAhvTransPortType)(this)).outputAhvTrans(inValue);
            return retVal.arrayOfTrans;
        }
    }
}
