//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratcolInterface.StratcolAuth {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
        ".wsdl", ConfigurationName="StratcolAuth.authenticateAccessPortType")]
    public interface authenticateAccessPortType {
        
        // CODEGEN: Generating message contract since the operation authenticateAccess is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="authenticateAccess", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratcolInterface.StratcolAuth.authenticateAccessResponse authenticateAccess(StratcolInterface.StratcolAuth.authenticateAccessRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
        ".wsdl")]
    public partial class authenticateClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
        ".wsdl")]
    public partial class authenticateAccess : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paramsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string @params {
            get {
                return this.paramsField;
            }
            set {
                this.paramsField = value;
                this.RaisePropertyChanged("params");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
        ".wsdl")]
    public partial class returnResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateAccessRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
            ".wsdl")]
        public StratcolInterface.StratcolAuth.authenticateClient authenticateClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
            ".wsdl", Order=0)]
        public StratcolInterface.StratcolAuth.authenticateAccess authenticateAccess;
        
        public authenticateAccessRequest() {
        }
        
        public authenticateAccessRequest(StratcolInterface.StratcolAuth.authenticateClient authenticateClient, StratcolInterface.StratcolAuth.authenticateAccess authenticateAccess) {
            this.authenticateClient = authenticateClient;
            this.authenticateAccess = authenticateAccess;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class authenticateAccessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorAuth" +
            ".wsdl", Order=0)]
        public StratcolInterface.StratcolAuth.returnResult returnResult;
        
        public authenticateAccessResponse() {
        }
        
        public authenticateAccessResponse(StratcolInterface.StratcolAuth.returnResult returnResult) {
            this.returnResult = returnResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface authenticateAccessPortTypeChannel : StratcolInterface.StratcolAuth.authenticateAccessPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class authenticateAccessPortTypeClient : System.ServiceModel.ClientBase<StratcolInterface.StratcolAuth.authenticateAccessPortType>, StratcolInterface.StratcolAuth.authenticateAccessPortType {
        
        public authenticateAccessPortTypeClient() {
        }
        
        public authenticateAccessPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public authenticateAccessPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticateAccessPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public authenticateAccessPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratcolInterface.StratcolAuth.authenticateAccessResponse StratcolInterface.StratcolAuth.authenticateAccessPortType.authenticateAccess(StratcolInterface.StratcolAuth.authenticateAccessRequest request) {
            return base.Channel.authenticateAccess(request);
        }
        
        public StratcolInterface.StratcolAuth.returnResult authenticateAccess(StratcolInterface.StratcolAuth.authenticateClient authenticateClient, StratcolInterface.StratcolAuth.authenticateAccess authenticateAccess1) {
            StratcolInterface.StratcolAuth.authenticateAccessRequest inValue = new StratcolInterface.StratcolAuth.authenticateAccessRequest();
            inValue.authenticateClient = authenticateClient;
            inValue.authenticateAccess = authenticateAccess1;
            StratcolInterface.StratcolAuth.authenticateAccessResponse retVal = ((StratcolInterface.StratcolAuth.authenticateAccessPortType)(this)).authenticateAccess(inValue);
            return retVal.returnResult;
        }
    }
}
