//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratcolInterface.StratcolSearchCanncelled {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
        "chCancellations.wsdl", ConfigurationName="StratcolSearchCanncelled.searchCancelledTransPortType")]
    public interface searchCancelledTransPortType {
        
        // CODEGEN: Generating message contract since the operation searchCancelledTrans is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="searchCancelledTrans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratcolInterface.StratcolSearchCanncelled.searchCancelledTransResponse searchCancelledTrans(StratcolInterface.StratcolSearchCanncelled.searchCancelledTransRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
        "chCancellations.wsdl")]
    public partial class authenticateClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
        "chCancellations.wsdl")]
    public partial class tran : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string user_idField;
        
        private string tran_typeField;
        
        private string dbt_cdt_idField;
        
        private string otidField;
        
        private string referenceField;
        
        private string batch_refField;
        
        private string nameField;
        
        private string account_noField;
        
        private string action_dateField;
        
        private string valueField;
        
        private string cancel_reasonField;
        
        private string cancel_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tran_type {
            get {
                return this.tran_typeField;
            }
            set {
                this.tran_typeField = value;
                this.RaisePropertyChanged("tran_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string dbt_cdt_id {
            get {
                return this.dbt_cdt_idField;
            }
            set {
                this.dbt_cdt_idField = value;
                this.RaisePropertyChanged("dbt_cdt_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string otid {
            get {
                return this.otidField;
            }
            set {
                this.otidField = value;
                this.RaisePropertyChanged("otid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string batch_ref {
            get {
                return this.batch_refField;
            }
            set {
                this.batch_refField = value;
                this.RaisePropertyChanged("batch_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string account_no {
            get {
                return this.account_noField;
            }
            set {
                this.account_noField = value;
                this.RaisePropertyChanged("account_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string action_date {
            get {
                return this.action_dateField;
            }
            set {
                this.action_dateField = value;
                this.RaisePropertyChanged("action_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string cancel_reason {
            get {
                return this.cancel_reasonField;
            }
            set {
                this.cancel_reasonField = value;
                this.RaisePropertyChanged("cancel_reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string cancel_date {
            get {
                return this.cancel_dateField;
            }
            set {
                this.cancel_dateField = value;
                this.RaisePropertyChanged("cancel_date");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
        "chCancellations.wsdl")]
    public partial class searchCancelledTrans : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cancel_date_fromField;
        
        private string cancel_date_toField;
        
        private string file_codeField;
        
        private string batch_refField;
        
        private string date_fromField;
        
        private string date_toField;
        
        private string account_noField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string cancel_date_from {
            get {
                return this.cancel_date_fromField;
            }
            set {
                this.cancel_date_fromField = value;
                this.RaisePropertyChanged("cancel_date_from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string cancel_date_to {
            get {
                return this.cancel_date_toField;
            }
            set {
                this.cancel_date_toField = value;
                this.RaisePropertyChanged("cancel_date_to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string file_code {
            get {
                return this.file_codeField;
            }
            set {
                this.file_codeField = value;
                this.RaisePropertyChanged("file_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string batch_ref {
            get {
                return this.batch_refField;
            }
            set {
                this.batch_refField = value;
                this.RaisePropertyChanged("batch_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string date_from {
            get {
                return this.date_fromField;
            }
            set {
                this.date_fromField = value;
                this.RaisePropertyChanged("date_from");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string date_to {
            get {
                return this.date_toField;
            }
            set {
                this.date_toField = value;
                this.RaisePropertyChanged("date_to");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string account_no {
            get {
                return this.account_noField;
            }
            set {
                this.account_noField = value;
                this.RaisePropertyChanged("account_no");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCancelledTransRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
            "chCancellations.wsdl")]
        public StratcolInterface.StratcolSearchCanncelled.authenticateClient authenticateClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
            "chCancellations.wsdl", Order=0)]
        public StratcolInterface.StratcolSearchCanncelled.searchCancelledTrans searchCancelledTrans;
        
        public searchCancelledTransRequest() {
        }
        
        public searchCancelledTransRequest(StratcolInterface.StratcolSearchCanncelled.authenticateClient authenticateClient, StratcolInterface.StratcolSearchCanncelled.searchCancelledTrans searchCancelledTrans) {
            this.authenticateClient = authenticateClient;
            this.searchCancelledTrans = searchCancelledTrans;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchCancelledTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorSear" +
            "chCancellations.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("tranDetails", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratcolInterface.StratcolSearchCanncelled.tran[] arrayOfTrans;
        
        public searchCancelledTransResponse() {
        }
        
        public searchCancelledTransResponse(StratcolInterface.StratcolSearchCanncelled.tran[] arrayOfTrans) {
            this.arrayOfTrans = arrayOfTrans;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface searchCancelledTransPortTypeChannel : StratcolInterface.StratcolSearchCanncelled.searchCancelledTransPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class searchCancelledTransPortTypeClient : System.ServiceModel.ClientBase<StratcolInterface.StratcolSearchCanncelled.searchCancelledTransPortType>, StratcolInterface.StratcolSearchCanncelled.searchCancelledTransPortType {
        
        public searchCancelledTransPortTypeClient() {
        }
        
        public searchCancelledTransPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public searchCancelledTransPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public searchCancelledTransPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public searchCancelledTransPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratcolInterface.StratcolSearchCanncelled.searchCancelledTransResponse StratcolInterface.StratcolSearchCanncelled.searchCancelledTransPortType.searchCancelledTrans(StratcolInterface.StratcolSearchCanncelled.searchCancelledTransRequest request) {
            return base.Channel.searchCancelledTrans(request);
        }
        
        public StratcolInterface.StratcolSearchCanncelled.tran[] searchCancelledTrans(StratcolInterface.StratcolSearchCanncelled.authenticateClient authenticateClient, StratcolInterface.StratcolSearchCanncelled.searchCancelledTrans searchCancelledTrans1) {
            StratcolInterface.StratcolSearchCanncelled.searchCancelledTransRequest inValue = new StratcolInterface.StratcolSearchCanncelled.searchCancelledTransRequest();
            inValue.authenticateClient = authenticateClient;
            inValue.searchCancelledTrans = searchCancelledTrans1;
            StratcolInterface.StratcolSearchCanncelled.searchCancelledTransResponse retVal = ((StratcolInterface.StratcolSearchCanncelled.searchCancelledTransPortType)(this)).searchCancelledTrans(inValue);
            return retVal.arrayOfTrans;
        }
    }
}
