//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratCorp.CorpSMS.Service.MessageService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary.DataCont" +
        "racts")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.SendMessage))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.DeliveryReport))]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateCreatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] EncryptedTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OriginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UniqueIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreated {
            get {
                return this.DateCreatedField;
            }
            set {
                if ((this.DateCreatedField.Equals(value) != true)) {
                    this.DateCreatedField = value;
                    this.RaisePropertyChanged("DateCreated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] EncryptedText {
            get {
                return this.EncryptedTextField;
            }
            set {
                if ((object.ReferenceEquals(this.EncryptedTextField, value) != true)) {
                    this.EncryptedTextField = value;
                    this.RaisePropertyChanged("EncryptedText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((this.MessageIdField.Equals(value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Number {
            get {
                return this.NumberField;
            }
            set {
                if ((object.ReferenceEquals(this.NumberField, value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OriginID {
            get {
                return this.OriginIDField;
            }
            set {
                if ((this.OriginIDField.Equals(value) != true)) {
                    this.OriginIDField = value;
                    this.RaisePropertyChanged("OriginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UniqueID {
            get {
                return this.UniqueIDField;
            }
            set {
                if ((this.UniqueIDField.Equals(value) != true)) {
                    this.UniqueIDField = value;
                    this.RaisePropertyChanged("UniqueID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SendMessage", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary.DataCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class SendMessage : StratCorp.CorpSMS.Service.MessageService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool FailedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FailedReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Failed {
            get {
                return this.FailedField;
            }
            set {
                if ((this.FailedField.Equals(value) != true)) {
                    this.FailedField = value;
                    this.RaisePropertyChanged("Failed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FailedReason {
            get {
                return this.FailedReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.FailedReasonField, value) != true)) {
                    this.FailedReasonField = value;
                    this.RaisePropertyChanged("FailedReason");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryReport", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary.DataCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class DeliveryReport : StratCorp.CorpSMS.Service.MessageService.Message {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private StratCorp.CorpSMS.Service.MessageService.MessageStatus[] MessageStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public StratCorp.CorpSMS.Service.MessageService.MessageStatus[] MessageStatus {
            get {
                return this.MessageStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageStatusField, value) != true)) {
                    this.MessageStatusField = value;
                    this.RaisePropertyChanged("MessageStatus");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageStatus", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary.DataCont" +
        "racts")]
    [System.SerializableAttribute()]
    public partial class MessageStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReasonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StatusDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Reason {
            get {
                return this.ReasonField;
            }
            set {
                if ((object.ReferenceEquals(this.ReasonField, value) != true)) {
                    this.ReasonField = value;
                    this.RaisePropertyChanged("Reason");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StatusDate {
            get {
                return this.StatusDateField;
            }
            set {
                if ((this.StatusDateField.Equals(value) != true)) {
                    this.StatusDateField = value;
                    this.RaisePropertyChanged("StatusDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
    [System.SerializableAttribute()]
    public partial class ServiceCallFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExceptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaultMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exception {
            get {
                return this.ExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionField, value) != true)) {
                    this.ExceptionField = value;
                    this.RaisePropertyChanged("Exception");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FaultMessage {
            get {
                return this.FaultMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageField, value) != true)) {
                    this.FaultMessageField = value;
                    this.RaisePropertyChanged("FaultMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MessageService.IMessageService")]
    public interface IMessageService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SendSingleSMS", ReplyAction="http://tempuri.org/IMessageService/SendSingleSMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/SendSingleSMSServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        StratCorp.CorpSMS.Service.MessageService.Message[] SendSingleSMS(StratCorp.CorpSMS.Service.MessageService.Message smsEntity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SendSMS", ReplyAction="http://tempuri.org/IMessageService/SendSMSResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/SendSMSServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        StratCorp.CorpSMS.Service.MessageService.Message[] SendSMS(StratCorp.CorpSMS.Service.MessageService.Message[] smsCollection);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SendQueuedMessages", ReplyAction="http://tempuri.org/IMessageService/SendQueuedMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/SendQueuedMessagesServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void SendQueuedMessages(System.Guid guid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/SendAllQueuedMessages", ReplyAction="http://tempuri.org/IMessageService/SendAllQueuedMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/SendAllQueuedMessagesServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void SendAllQueuedMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/RefreshDeliveryReport", ReplyAction="http://tempuri.org/IMessageService/RefreshDeliveryReportResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/RefreshDeliveryReportServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void RefreshDeliveryReport();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/RefreshCredits", ReplyAction="http://tempuri.org/IMessageService/RefreshCreditsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/RefreshCreditsServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void RefreshCredits();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/RefreshReplies", ReplyAction="http://tempuri.org/IMessageService/RefreshRepliesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/RefreshRepliesServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void RefreshReplies();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/RefreshShortCodes", ReplyAction="http://tempuri.org/IMessageService/RefreshShortCodesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/RefreshShortCodesServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        void RefreshShortCodes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetDeliveryReports", ReplyAction="http://tempuri.org/IMessageService/GetDeliveryReportsResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/GetDeliveryReportsServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        StratCorp.CorpSMS.Service.MessageService.DeliveryReport[] GetDeliveryReports();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetDeliveryReportByOriginId", ReplyAction="http://tempuri.org/IMessageService/GetDeliveryReportByOriginIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/GetDeliveryReportByOriginIdServiceCallFaultFau" +
            "lt", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        StratCorp.CorpSMS.Service.MessageService.DeliveryReport[] GetDeliveryReportByOriginId(int originId, int uniqueId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageService/GetShortCodeMessages", ReplyAction="http://tempuri.org/IMessageService/GetShortCodeMessagesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(StratCorp.CorpSMS.Service.MessageService.ServiceCallFault), Action="http://tempuri.org/IMessageService/GetShortCodeMessagesServiceCallFaultFault", Name="ServiceCallFault", Namespace="http://schemas.datacontract.org/2004/07/StratCorp.CorpSMS.ServiceLibrary")]
        StratCorp.CorpSMS.Service.MessageService.Message[] GetShortCodeMessages(System.DateTime startTime, System.DateTime endTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageServiceChannel : StratCorp.CorpSMS.Service.MessageService.IMessageService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageServiceClient : System.ServiceModel.ClientBase<StratCorp.CorpSMS.Service.MessageService.IMessageService>, StratCorp.CorpSMS.Service.MessageService.IMessageService {
        
        public MessageServiceClient() {
        }
        
        public MessageServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MessageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StratCorp.CorpSMS.Service.MessageService.Message[] SendSingleSMS(StratCorp.CorpSMS.Service.MessageService.Message smsEntity) {
            return base.Channel.SendSingleSMS(smsEntity);
        }
        
        public StratCorp.CorpSMS.Service.MessageService.Message[] SendSMS(StratCorp.CorpSMS.Service.MessageService.Message[] smsCollection) {
            return base.Channel.SendSMS(smsCollection);
        }
        
        public void SendQueuedMessages(System.Guid guid) {
            base.Channel.SendQueuedMessages(guid);
        }
        
        public void SendAllQueuedMessages() {
            base.Channel.SendAllQueuedMessages();
        }
        
        public void RefreshDeliveryReport() {
            base.Channel.RefreshDeliveryReport();
        }
        
        public void RefreshCredits() {
            base.Channel.RefreshCredits();
        }
        
        public void RefreshReplies() {
            base.Channel.RefreshReplies();
        }
        
        public void RefreshShortCodes() {
            base.Channel.RefreshShortCodes();
        }
        
        public StratCorp.CorpSMS.Service.MessageService.DeliveryReport[] GetDeliveryReports() {
            return base.Channel.GetDeliveryReports();
        }
        
        public StratCorp.CorpSMS.Service.MessageService.DeliveryReport[] GetDeliveryReportByOriginId(int originId, int uniqueId) {
            return base.Channel.GetDeliveryReportByOriginId(originId, uniqueId);
        }
        
        public StratCorp.CorpSMS.Service.MessageService.Message[] GetShortCodeMessages(System.DateTime startTime, System.DateTime endTime) {
            return base.Channel.GetShortCodeMessages(startTime, endTime);
        }
    }
}
