//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratcolInterface.StratcolCodes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
        "s.wsdl", ConfigurationName="StratcolCodes.integratorCodesPortType")]
    public interface integratorCodesPortType {
        
        // CODEGEN: Generating message contract since the operation integratorCodes is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="integratorCodes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratcolInterface.StratcolCodes.integratorCodesResponse integratorCodes(StratcolInterface.StratcolCodes.integratorCodesRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
        "s.wsdl")]
    public partial class authenticateClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
        "s.wsdl")]
    public partial class outputDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
        "s.wsdl")]
    public partial class inputList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string list_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string list_type {
            get {
                return this.list_typeField;
            }
            set {
                this.list_typeField = value;
                this.RaisePropertyChanged("list_type");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class integratorCodesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
            "s.wsdl")]
        public StratcolInterface.StratcolCodes.authenticateClient authenticateClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
            "s.wsdl", Order=0)]
        public StratcolInterface.StratcolCodes.inputList inputList;
        
        public integratorCodesRequest() {
        }
        
        public integratorCodesRequest(StratcolInterface.StratcolCodes.authenticateClient authenticateClient, StratcolInterface.StratcolCodes.inputList inputList) {
            this.authenticateClient = authenticateClient;
            this.inputList = inputList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class integratorCodesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorCode" +
            "s.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratcolInterface.StratcolCodes.outputDesc[] list;
        
        public integratorCodesResponse() {
        }
        
        public integratorCodesResponse(StratcolInterface.StratcolCodes.outputDesc[] list) {
            this.list = list;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface integratorCodesPortTypeChannel : StratcolInterface.StratcolCodes.integratorCodesPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class integratorCodesPortTypeClient : System.ServiceModel.ClientBase<StratcolInterface.StratcolCodes.integratorCodesPortType>, StratcolInterface.StratcolCodes.integratorCodesPortType {
        
        public integratorCodesPortTypeClient() {
        }
        
        public integratorCodesPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public integratorCodesPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integratorCodesPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public integratorCodesPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratcolInterface.StratcolCodes.integratorCodesResponse StratcolInterface.StratcolCodes.integratorCodesPortType.integratorCodes(StratcolInterface.StratcolCodes.integratorCodesRequest request) {
            return base.Channel.integratorCodes(request);
        }
        
        public StratcolInterface.StratcolCodes.outputDesc[] integratorCodes(StratcolInterface.StratcolCodes.authenticateClient authenticateClient, StratcolInterface.StratcolCodes.inputList inputList) {
            StratcolInterface.StratcolCodes.integratorCodesRequest inValue = new StratcolInterface.StratcolCodes.integratorCodesRequest();
            inValue.authenticateClient = authenticateClient;
            inValue.inputList = inputList;
            StratcolInterface.StratcolCodes.integratorCodesResponse retVal = ((StratcolInterface.StratcolCodes.integratorCodesPortType)(this)).integratorCodes(inValue);
            return retVal.list;
        }
    }
}
