// <auto-generated />
namespace Aroma_Violet.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EvenMorelookupchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EvenMorelookupchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201508051341159_Even More lookup changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
