//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StratcolInterface.StratcolRejected {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
        "cted.wsdl", ConfigurationName="StratcolRejected.rejectedStandardTransPortType")]
    public interface rejectedStandardTransPortType {
        
        // CODEGEN: Generating message contract since the operation rejectedStandardTrans is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="rejectedStandardTrans", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        StratcolInterface.StratcolRejected.rejectedStandardTransResponse rejectedStandardTrans(StratcolInterface.StratcolRejected.rejectedStandardTransRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
        "cted.wsdl")]
    public partial class authenticateClient : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private string modeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                this.modeField = value;
                this.RaisePropertyChanged("mode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
        "cted.wsdl")]
    public partial class tranDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string user_idField;
        
        private string tran_statusField;
        
        private string acb_statusField;
        
        private string acb_reasonField;
        
        private string acb_reason_codeField;
        
        private string tran_typeField;
        
        private string dbt_cdt_idField;
        
        private string otidField;
        
        private string referenceField;
        
        private string batch_refField;
        
        private string nameField;
        
        private string account_noField;
        
        private string action_dateField;
        
        private string status_dateField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string user_id {
            get {
                return this.user_idField;
            }
            set {
                this.user_idField = value;
                this.RaisePropertyChanged("user_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string tran_status {
            get {
                return this.tran_statusField;
            }
            set {
                this.tran_statusField = value;
                this.RaisePropertyChanged("tran_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string acb_status {
            get {
                return this.acb_statusField;
            }
            set {
                this.acb_statusField = value;
                this.RaisePropertyChanged("acb_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string acb_reason {
            get {
                return this.acb_reasonField;
            }
            set {
                this.acb_reasonField = value;
                this.RaisePropertyChanged("acb_reason");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string acb_reason_code {
            get {
                return this.acb_reason_codeField;
            }
            set {
                this.acb_reason_codeField = value;
                this.RaisePropertyChanged("acb_reason_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string tran_type {
            get {
                return this.tran_typeField;
            }
            set {
                this.tran_typeField = value;
                this.RaisePropertyChanged("tran_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string dbt_cdt_id {
            get {
                return this.dbt_cdt_idField;
            }
            set {
                this.dbt_cdt_idField = value;
                this.RaisePropertyChanged("dbt_cdt_id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string otid {
            get {
                return this.otidField;
            }
            set {
                this.otidField = value;
                this.RaisePropertyChanged("otid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
                this.RaisePropertyChanged("reference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string batch_ref {
            get {
                return this.batch_refField;
            }
            set {
                this.batch_refField = value;
                this.RaisePropertyChanged("batch_ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string account_no {
            get {
                return this.account_noField;
            }
            set {
                this.account_noField = value;
                this.RaisePropertyChanged("account_no");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string action_date {
            get {
                return this.action_dateField;
            }
            set {
                this.action_dateField = value;
                this.RaisePropertyChanged("action_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string status_date {
            get {
                return this.status_dateField;
            }
            set {
                this.status_dateField = value;
                this.RaisePropertyChanged("status_date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
        "cted.wsdl")]
    public partial class outputRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string file_codeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string file_code {
            get {
                return this.file_codeField;
            }
            set {
                this.file_codeField = value;
                this.RaisePropertyChanged("file_code");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rejectedStandardTransRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
            "cted.wsdl")]
        public StratcolInterface.StratcolRejected.authenticateClient authenticateClient;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
            "cted.wsdl", Order=0)]
        public StratcolInterface.StratcolRejected.outputRequest outputRequest;
        
        public rejectedStandardTransRequest() {
        }
        
        public rejectedStandardTransRequest(StratcolInterface.StratcolRejected.authenticateClient authenticateClient, StratcolInterface.StratcolRejected.outputRequest outputRequest) {
            this.authenticateClient = authenticateClient;
            this.outputRequest = outputRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class rejectedStandardTransResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://live.stratcol.co.za/dynamic/administration/serv_manager/sysIntegratorReje" +
            "cted.wsdl", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("trans", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StratcolInterface.StratcolRejected.tranDetails[] arrayOfTrans;
        
        public rejectedStandardTransResponse() {
        }
        
        public rejectedStandardTransResponse(StratcolInterface.StratcolRejected.tranDetails[] arrayOfTrans) {
            this.arrayOfTrans = arrayOfTrans;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface rejectedStandardTransPortTypeChannel : StratcolInterface.StratcolRejected.rejectedStandardTransPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class rejectedStandardTransPortTypeClient : System.ServiceModel.ClientBase<StratcolInterface.StratcolRejected.rejectedStandardTransPortType>, StratcolInterface.StratcolRejected.rejectedStandardTransPortType {
        
        public rejectedStandardTransPortTypeClient() {
        }
        
        public rejectedStandardTransPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public rejectedStandardTransPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rejectedStandardTransPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public rejectedStandardTransPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        StratcolInterface.StratcolRejected.rejectedStandardTransResponse StratcolInterface.StratcolRejected.rejectedStandardTransPortType.rejectedStandardTrans(StratcolInterface.StratcolRejected.rejectedStandardTransRequest request) {
            return base.Channel.rejectedStandardTrans(request);
        }
        
        public StratcolInterface.StratcolRejected.tranDetails[] rejectedStandardTrans(StratcolInterface.StratcolRejected.authenticateClient authenticateClient, StratcolInterface.StratcolRejected.outputRequest outputRequest) {
            StratcolInterface.StratcolRejected.rejectedStandardTransRequest inValue = new StratcolInterface.StratcolRejected.rejectedStandardTransRequest();
            inValue.authenticateClient = authenticateClient;
            inValue.outputRequest = outputRequest;
            StratcolInterface.StratcolRejected.rejectedStandardTransResponse retVal = ((StratcolInterface.StratcolRejected.rejectedStandardTransPortType)(this)).rejectedStandardTrans(inValue);
            return retVal.arrayOfTrans;
        }
    }
}
